### PR TITLE
Moved options in chartOptions and changed view (tag and JS)

### PR DESCRIPTION
**Pull request by funkycram**

### CODE REVIEW

**Comment by onmotion** [comment]
Hi!

What is the main purpose of this change? It breaks backward compatibility

**Comment by funkycram** [comment]
Yes, maybe I could change it to make it compatible with previous version.

2 reasons for this PR:
- the actual version doesn't work for me: `new Vue()` doesn't works whereas `new ApexCharts()` does, as indicated in the doc https://apexcharts.com/docs/creating-first-javascript-chart/
- It's better if `chartOptions` reflects the options of the documentation and the array structure (e.g `type` should be in `chart`: https://apexcharts.com/docs/options/chart/type/)

But if you prefer, I can push another PR that keeps the options `type`, `width`, `height` and `series`.
`timeout` should be removed, as `$(function (){})` already waits for the elements to load, or is there another reason?

**Comment by onmotion** [comment]
Basically, you are right. But this module based on [vue-apexcharts]( https://github.com/apexcharts/vue-apexcharts) (not raw ApexCharts)
That parameter structure like vue-apexchart module requires https://github.com/onmotion/yii2-widget-apexcharts/blob/master/assets/src/App.vue
and its should works because of this is build in bundle that contains Vue and vue-apexcharts both.

The reason of timeout, I assume, is speed up page loading without possible lag. You can set it to 0.
Actually I don't work with Yii2 and PHP anymore and can be wrong.

You are rewrite a module without Vue and it deserves its own module

**Comment by funkycram** [comment]
Yes, I understand, but I didn't managed to make it work with App.vue.
So this PR can be closed, thanks for your answers and the widget!

**Pull request closed without merging**
